<DOCFLEX_TEMPLATE VER='1.9'>
CREATED='2004-06-21 01:50:00'
LAST_UPDATE='2007-06-30 06:10:51'
DESIGNER_TOOL='DocFlex SDK 1.x'
TEMPLATE_TYPE='DocumentTemplate'
DSM_TYPE_ID='xsddoc'
ROOT_ET='xs:schema'
<TEMPLATE_PARAMS>
	PARAM={
		param.name='doc.schema.profile';
		param.displayName='Schema Profile';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.annotation';
		param.displayName='Annotation';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.element';
		param.displayName='Element Summary';
		param.type='enum';
		param.enum.values='all\nglobal\nlocal\nglobal_local\nnone';
	}
	PARAM={
		param.name='doc.schema.cs.complexType';
		param.displayName='Complex Type Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.simpleType';
		param.displayName='Simple Type Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.group';
		param.displayName='Element Group Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.attribute';
		param.displayName='Global Attribute Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.attributeGroup';
		param.displayName='Attribute Group Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.xmlSource';
		param.displayName='XML Source';
		param.description='Specifies if the XML source of the whole XML schema should be reproduced within the <i>Schema Overview</i> documentation.';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='sec.xmlSource.box.schema';
		param.displayName='Enclose in box';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='sec.xmlSource.remove.ann.schema';
		param.displayName='Remove <xs:annotation> elements';
		param.type='boolean';
	}
</TEMPLATE_PARAMS>
<HTARGET>
	HKEYS={
		'contextElement.id';
		'"detail"';
	}
</HTARGET>
<HTARGET>
	HKEYS={
		'getXMLDocument().id';
		'"detail"';
	}
</HTARGET>
FMT={
	doc.lengthUnits='pt';
	doc.hlink.style.link='cs3';
}
<STYLES>
	CHAR_STYLE={
		style.name='Code';
		style.id='cs1';
		text.font.name='Courier New';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Default Paragraph Font';
		style.id='cs2';
		style.default='true';
	}
	PAR_STYLE={
		style.name='Detail Heading 1';
		style.id='s1';
		text.font.size='12';
		text.font.style.bold='true';
		par.bkgr.opaque='true';
		par.bkgr.color='#CCCCFF';
		par.border.style='solid';
		par.border.color='#666666';
		par.margin.top='12';
		par.margin.bottom='10';
		par.padding.left='2.5';
		par.padding.right='2.5';
		par.padding.top='2';
		par.padding.bottom='2';
		par.page.keepWithNext='true';
	}
	PAR_STYLE={
		style.name='Detail Heading 2';
		style.id='s2';
		text.font.size='10';
		text.font.style.bold='true';
		par.bkgr.opaque='true';
		par.bkgr.color='#EEEEFF';
		par.border.style='solid';
		par.border.color='#666666';
		par.margin.top='12';
		par.margin.bottom='10';
		par.padding.left='2';
		par.padding.right='2';
		par.padding.top='2';
		par.padding.bottom='2';
		par.page.keepWithNext='true';
	}
	CHAR_STYLE={
		style.name='Hyperlink';
		style.id='cs3';
		text.decor.underline='true';
		text.color.foreground='#0000FF';
	}
	CHAR_STYLE={
		style.name='Internal Subset';
		style.id='cs4';
		text.font.name='Courier New';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Main Heading';
		style.id='s3';
		text.font.name='Verdana';
		text.font.size='13';
		text.font.style.bold='true';
		text.color.foreground='#4477AA';
		par.bkgr.opaque='true';
		par.bkgr.color='#EEEEEE';
		par.border.style='solid';
		par.border.color='#4477AA';
		par.margin.top='0';
		par.margin.bottom='9';
		par.padding.left='5';
		par.padding.right='5';
		par.padding.top='3';
		par.padding.bottom='3';
		par.page.keepTogether='true';
		par.page.keepWithNext='true';
	}
	CHAR_STYLE={
		style.name='Markup';
		style.id='cs5';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Normal';
		style.id='s4';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Normal Smaller';
		style.id='cs6';
		text.font.name='Arial';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Note Font';
		style.id='cs7';
		text.font.name='Arial';
		text.font.size='8';
		text.font.style.bold='false';
		par.lineHeight='11';
		par.margin.right='7';
	}
	CHAR_STYLE={
		style.name='Page Header Font';
		style.id='cs8';
		text.font.name='Arial';
		text.font.style.italic='true';
	}
	CHAR_STYLE={
		style.name='Page Number';
		style.id='cs9';
		text.font.size='9';
		text.font.style.italic='true';
	}
	CHAR_STYLE={
		style.name='Summary Heading Font';
		style.id='cs10';
		text.font.size='12';
		text.font.style.bold='true';
	}
	CHAR_STYLE={
		style.name='XML Source';
		style.id='cs11';
		text.font.name='Verdana';
		text.font.size='8';
	}
</STYLES>
<PAGE_HEADER>
	<AREA_SEC>
		FMT={
			text.style='cs8';
			table.cellpadding.both='0';
			table.border.style='none';
			table.border.bottom.style='solid';
		}
		<AREA>
			<CTRL_GROUP>
				FMT={
					par.border.bottom.style='solid';
				}
				<CTRLS>
					<LABEL>
						TEXT='XML Schema'
					</LABEL>
					<DATA_CTRL>
						FORMULA='\'"\' + getXMLDocument().getAttrStringValue("xmlName") + \'"\''
					</DATA_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
</PAGE_HEADER>
<ROOT>
	<AREA_SEC>
		FMT={
			par.style='s3';
		}
		<AREA>
			<CTRL_GROUP>
				<CTRLS>
					<LABEL>
						TEXT='XML Schema'
					</LABEL>
					<DATA_CTRL>
						FMT={
							text.font.style.italic='true';
						}
						FORMULA='\'"\' + getXMLDocument().getAttrStringValue("xmlName") + \'"\''
					</DATA_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
	<TEMPLATE_CALL>
		COND='getBooleanParam("doc.schema.profile")'
		FMT={
			sec.spacing.before='12';
		}
		TEMPLATE_FILE='schemaProfile.tpl'
		PASSED_PARAMS={
			'schema-summary','true';
		}
	</TEMPLATE_CALL>
	<FOLDER>
		DESCR='Annotation'
		COND='getBooleanParam("doc.schema.annotation")'
		COLLAPSED
		<BODY>
			<TEMPLATE_CALL>
				TEMPLATE_FILE='../ann/annotation.tpl'
			</TEMPLATE_CALL>
		</BODY>
		<HEADER>
			<AREA_SEC>
				FMT={
					par.style='s2';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							trow.bkgr.color='#CCCCFF';
						}
						<CTRLS>
							<LABEL>
								TEXT='Annotation'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<FOLDER>
		DESCR='COMPONENT SUMMARY'
		FMT={
			sec.spacing.before='14';
		}
		COLLAPSED
		<BODY>
			<TEMPLATE_CALL>
				DESCR='all elements'
				COND='getStringParam("doc.schema.cs.element") == "all"'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='allElementSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='global elements'
				COND='param = getStringParam("doc.schema.cs.element");\nparam == "global" || param == "global_local"'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='globalElementSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='local elements'
				COND='param = getStringParam("doc.schema.cs.element");\nparam == "local" || param == "global_local"'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='localElementSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='complexTypes'
				COND='getBooleanParam("doc.schema.cs.complexType")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='complexTypeSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='simpleTypes'
				COND='getBooleanParam("doc.schema.cs.simpleType")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='simpleTypeSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='element groups'
				COND='getBooleanParam("doc.schema.cs.group")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='groupSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='attributes'
				COND='getBooleanParam("doc.schema.cs.attribute")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='attributeSummary.tpl'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='attribute groups'
				COND='getBooleanParam("doc.schema.cs.attributeGroup")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='attributeGroupSummary.tpl'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		DESCR='XML SOURCE'
		COND='getBooleanParam("doc.schema.xmlSource")'
		CONTEXT_ELEMENT_EXPR='getXMLDocument()'
		MATCHING_ET='#DOCUMENT'
		FMT={
			sec.spacing.before='14';
		}
		<HTARGET>
			HKEYS={
				'contextElement.id';
				'"xml-source"';
			}
		</HTARGET>
		COLLAPSED
		<BODY>
			<AREA_SEC>
				COND='getBooleanParam("sec.xmlSource.box.schema")'
				FMT={
					sec.outputStyle='table';
					table.sizing='Relative';
					table.autofit='false';
					table.cellpadding.both='5';
					table.bkgr.color='#F5F5F5';
					table.border.style='solid';
					table.border.color='#999999';
					table.option.borderStylesInHTML='true';
				}
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<SS_CALL_CTRL>
								FMT={
									ctrl.size.width='499.5';
									ctrl.size.height='17.3';
								}
								SS_NAME='XML Source'
							</SS_CALL_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<SS_CALL>
				COND='! getBooleanParam("sec.xmlSource.box.schema")'
				SS_NAME='XML Source'
			</SS_CALL>
		</BODY>
		<HEADER>
			<AREA_SEC>
				FMT={
					par.style='s1';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							trow.bkgr.color='#CCCCFF';
						}
						<CTRLS>
							<LABEL>
								TEXT='XML Source'
							</LABEL>
							<DELIMITER>
								FMT={
									text.style='cs1';
								}
							</DELIMITER>
							<TEMPLATE_CALL_CTRL>
								FMT={
									text.style='cs7';
								}
								TEMPLATE_FILE='../xml/sourceNote.tpl'
								PASSED_PARAMS={
									'remove.annotations','getBooleanParam("sec.xmlSource.remove.ann.schema")';
								}
							</TEMPLATE_CALL_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<TEMPLATE_CALL>
		DESCR='Bottom Message'
		COND='output.type == "document"'
		TEMPLATE_FILE='../about.tpl'
	</TEMPLATE_CALL>
</ROOT>
<STOCK_SECTIONS>
	<FOLDER>
		MATCHING_ET='#DOCUMENT'
		SS_NAME='XML Source'
		<BODY>
			<AREA_SEC>
				DESCR='XML declaration'
				COND='getAttrValue("xmlDecl") != ""'
				FMT={
					text.style='cs11';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							txtfl.delimiter.type='none';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									text.style='cs5';
								}
								ATTR='xmlDecl'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<ELEMENT_ITER>
				DESCR='iterates by all nodes in the XML'
				FMT={
					text.style='cs11';
				}
				TARGET_ET='<ANY>'
				SCOPE='simple-location-rules'
				RULES={
					'* -> *';
				}
				<BODY>
					<FOLDER>
						DESCR='processes <!DOCTYPE> node'
						MATCHING_ET='#DOCTYPE'
						<BODY>
							<AREA_SEC>
								DESCR='simple case of <!DOCTYPE> node'
								COND='getAttrStringValue("internalSubset") == ""'
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='<!DOCTYPE'
											</LABEL>
											<DATA_CTRL>
												FMT={
													text.style='cs5';
												}
												ATTR='name'
											</DATA_CTRL>
											<PANEL>
												COND='getAttrStringValue("publicId") != ""'
												FMT={
													ctrl.size.width='132';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='PUBLIC'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='publicId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<PANEL>
												COND='getAttrStringValue("systemId") != ""'
												FMT={
													ctrl.size.width='137.3';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																COND='getAttrStringValue("publicId") == ""'
																FMT={
																	text.style='cs5';
																}
																TEXT='SYSTEM'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='systemId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<DELIMITER>
												FMT={
													text.style='cs5';
													txtfl.delimiter.type='none';
												}
											</DELIMITER>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='>'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<AREA_SEC>
								DESCR='<!DOCTYPE> node with Internal Subset'
								COND='getAttrStringValue("internalSubset") != ""'
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='<!DOCTYPE'
											</LABEL>
											<DATA_CTRL>
												FMT={
													text.style='cs5';
												}
												ATTR='name'
											</DATA_CTRL>
											<PANEL>
												COND='getAttrStringValue("publicId") != ""'
												FMT={
													ctrl.size.width='130.5';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='PUBLIC'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='publicId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<PANEL>
												COND='getAttrStringValue("systemId") != ""'
												FMT={
													ctrl.size.width='137.3';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																COND='getAttrStringValue("publicId") == ""'
																FMT={
																	text.style='cs5';
																}
																TEXT='SYSTEM'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='systemId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='['
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
									<CTRL_GROUP>
										FMT={
											par.margin.left='10';
										}
										<CTRLS>
											<DATA_CTRL>
												FMT={
													ctrl.option.text.trimSpaces='true';
													text.style='cs4';
													text.option.renderNLs='true';
												}
												ATTR='internalSubset'
											</DATA_CTRL>
										</CTRLS>
									</CTRL_GROUP>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT=']>'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</FOLDER>
					<TEMPLATE_CALL>
						DESCR='processes other XML nodes'
						COND='sectionBlock.execSecNone'
						TEMPLATE_FILE='../xml/nodeSource.tpl'
						PASSED_PARAMS={
							'bookmark.elements','true';
							'bookmark.xmlns','true';
							'remove.annotations','getBooleanParam("sec.xmlSource.remove.ann.schema")';
						}
					</TEMPLATE_CALL>
				</BODY>
			</ELEMENT_ITER>
		</BODY>
	</FOLDER>
</STOCK_SECTIONS>
CHECKSUM='F+SiU3PFiwCAJoTuyJs?HA'
</DOCFLEX_TEMPLATE>